name = "ai-platform"
main = "src/index.js"
compatibility_date = "2023-12-01"

[site]
bucket = "./public"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "ai_platform_db"
database_id = "ai-platform-db"

[env.production]
workers_dev = false
route = "ai-platform.example.com/*"
